### ISSUE TITLE
How to sort entity?

### ISSUE THREAD

**Issue by wilhantian** [JoebRogers/PICO-EC#1]
I`m making a Top-down game, the entities need to sort draw.

**Comment by JoebRogers** [comment]
@wilhantian Hey, sorry for the late response - this issue was buried in my list and I totally missed it. Assuming you've not tackled this already, you can manually sort the entities rather easily (there's no built-in way to handle this as the framework was intended to be quite skeletal). 

You can choose to sort the table storing the entities in-place via a temporary array (I'd recommend `table.sort` to trivialise this further, but off the top of my head I'm not sure if Pico-8 implements this method or not), or you can implement your own `spair` function for returning a sorted set of pairs from the existing `_scene._entities` table without impairing the default ordering.

You'll want to do your own research on the particular sorting algorithm you want to use for your game, whether that's a simple Z-ordered approach based on a transform component, or if you want to take a more multi-tiered approach based on absolute positioning + layers, etc.

I'll think about implement an easy way of sorting entities in the scene for drawing in the meantime.
